### ISSUE TITLE
吹更

### ISSUE THREAD

**Issue by oatiz** [archerfeel/azeroth-vm#1]
:neckbeard:

**Comment by bytesnail** [comment]
催更。。。错字受

**Comment by bytesnail** [comment]
另外，作者是中国人吗，他可能看不懂中文，建议英文沟通

**Comment by kb1ns** [comment]
@oatiz 最近每天都在更新了，近期主要是把原来的 用方法调用的形式模拟jvm方法调用改成了原生的 stack压栈出栈，当前java方法始终对应栈顶frame，因为rust总所周知的原因
stack: Vec<Frame>, 在执行当前方法时需要&mut ref stack, 而入栈同样需要&mut ref，所以花了很多精力通过编译。
